<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="E_vision_task.WebForm1" EnableEventValidation="false" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="StyleSheet1.css" type="text/css" rel="stylesheet" />
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="cd-main-content">
    <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
<a class="navbar-brand" href="#mypage">Product items</a>
        </div>
        <div class="collapse navbar-collapse" id="mynavbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="Home.aspx">Home</a></li>
                <li><a href="viewer.aspx">View items</a></li>
                <li><a href="WebForm1.aspx">Edit items</a></li>
            </ul>
        </div>
    </div>
        </nav>
        </div>
    <form id="form1" runat="server">
        <div id="div1">
                        <asp:Label ID="Label2" runat="server">Name :</asp:Label>
                        <br />
                        <br />
              <asp:TextBox ID="TextBox1" runat="server" placeholder="Enter Product name..." Height="25px" Width="260px"></asp:TextBox>
                        <br />
                        <br />
              <asp:Label ID="Label4" runat="server">Photo :</asp:Label>
                        <br />
                        <asp:FileUpload ID="FileUpload1" runat="server" Height="29px" Width="272px" style="margin-left: 0px" />

<%--           <asp:Button id="UploadBtn" Text="Upload Me!" OnClick="btnAdd_Click" runat="server"></asp:Button>--%>
                        <br />
                        <br />
                        <asp:Label ID="Label3" runat="server" >Price :</asp:Label>
                        <br />
                        <br />
              <asp:TextBox ID="TextBox2" runat="server" placeholder="Enter Product price..." Width="260px" Height="25px"></asp:TextBox>
                                    <br />
                                    <br />
                        <asp:Label ID="Label5" runat="server" >LastUpdated :</asp:Label>
                        <br />
                        <br />
              <asp:TextBox ID="TextBox3" runat="server" placeholder="Enter lastupdate date..." Width="261px" Height="25px"></asp:TextBox>
                        <br />
                        <br />
                        <br />
             <asp:Button ID="Button1" runat="server" Text="Add new Product" OnClick="btnAdd_Click" Height="47px" Width="188px"/>
                        <br />
                        <br />
                        <br />
             <asp:Button ID="Button2" runat="server" Text="Update Product" OnClick="btnedit_Click" Height="46px" Width="191px"/>
                          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:Label ID="Label6" runat="server">ID :</asp:Label>
                        &nbsp;
             <asp:TextBox ID="TextBox4" runat="server"  placeholder="Enter Product id..." Height="25px" Width="244px"></asp:TextBox>

        </div>
        <hr />
    <div class="div3">
                      <asp:Label ID="Label1" runat="server" style="border:2px solid black;padding:10px 3px;"> Products Form </asp:Label>
                      <br />
                      <br />
                      <asp:Label ID="Label7" runat="server">Search for Products :</asp:Label>
            &nbsp;
            <asp:TextBox ID="txtSearch" runat="server" AutoPostBack="true"  placeholder="Enter Product name..."></asp:TextBox>&nbsp;&nbsp;&nbsp; <asp:Button ID="Button6" runat="server" Text="Search" OnClick="Search" Height="47px" Width="117px"/>
                      <br /><br />
            <asp:Button ID="Button5" runat="server" Text="Export" OnClick="btnexport_Click" Height="47px" Width="188px"/>
             <asp:GridView ID="GridView1" runat="server" Height="245px" Width="585px" DataKeyNames="ID" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="False" CellPadding="4" GridLines="None" style="margin-left: 356px; margin-top: 45px" ForeColor="#333333">
                     <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                 <Columns>  
                         <asp:BoundField DataField="id" HeaderText="id" /> 
                         <asp:BoundField DataField="Name" HeaderText="Name" />
                         <asp:ImageField AccessibleHeaderText="Photo" DataImageUrlField="Photo" HeaderText="Photo">
                             <ControlStyle Font-Size="Small" Height="50px" Width="50px" />
                         </asp:ImageField>
                         <asp:BoundField DataField="Price" HeaderText="Price" /> 
                         <asp:BoundField DataField="LastUpdated" HeaderText="LastUpdated" />
           
                 </Columns>
                     <EditRowStyle BackColor="#999999" />
                     <FooterStyle BackColor="#5D7B9D" ForeColor="White" Font-Bold="True" />
                     <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                     <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                     <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                     <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                     <SortedAscendingCellStyle BackColor="#E9E7E2" />
                     <SortedAscendingHeaderStyle BackColor="#506C8C" />
                     <SortedDescendingCellStyle BackColor="#FFFDF8" />
                     <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
           
    </div>
    </form>

     <script>
         $(document).ready(function () {
             $(window).scroll(function () {
                 $(".div3").each(function () {
                     var pos = $(this).offset().top;

                     var winTop = $(window).scrollTop();
                     if (pos < winTop + 600) {
                         $(this).addClass("slide");
                     }
                 });
             });
             });
      </script>
</body>
</html>
